### ISSUE TITLE
Why is the data.json not in .gitignore

### ISSUE THREAD

**Issue by kymppi** [raikasdev/thecakeisalie#1]
I'd guess its a file generated by the project so why does it already exists?

**Comment by raikasdev** [comment]
data.json is the output that the program outputs for the script, that the
website fetches

**Comment by kymppi** [comment]
It is quite badly explained what the data.json contains, i saw it has stars and other info but from what repo?

**Comment by raikasdev** [comment]
It git pulls all ritta repos (server, next, shared), then goes thru all .ts, .js, .tsx .jsx files and calculates line count for them. Then it fetches the commit count and the language summary and fetches a random one of them. THIS IS A RANDOM SIDE PROJECT THAT I WONT DOCUMENT

**Comment by kymppi** [comment]
I know its a side project, but everything should be documented, you'll thank yourself in the future 
![contabo](https://user-images.githubusercontent.com/48528700/155880964-8f110cae-70a9-4960-bbcd-0a5c7866509d.png)
